// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BarcodeReaderController from "./barcode_reader_controller"
application.register("barcode-reader", BarcodeReaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomepageWebController from "./homepage_web_controller"
application.register("homepage-web", HomepageWebController)

import MapController from "./map_controller"
application.register("map", MapController)
