databases:
  - name: illuminate
    databaseName: illuminate_production
    user: illuminate

services:
  - type: web
    name: illuminate
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: illuminate
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
