meta_name: "Illuminate"
meta_title: "Illuminate - Enhancing the beauty experience for all"
meta_description: "Illuminate is an app that improves the beauty shopping experience for visually-impaired persons with a simple scan from a mobile device."
meta_image: "cover.png"
